### ISSUE TITLE
One of the styles does not work.

### ISSUE THREAD

**Issue by jaxk25** [IAM-1GRJK/Example-Webpage#3]
The **green_on_black.css** in the _static_ folder does not work. It displays the same results as the **black_on_white.css** in the _static_ folder.
The code in the green_on_black.css is:
`body {
	background: black;
	color: green;
}
`
whereas the black_on_white code looks like this:
`body {
	background: white;
	color: white;
}
`
You can quite clearly see that the background and color lines are different and display the correct color.
Although, this isn't the same when using that style on a html page.
Thank you,
@jaxk25

**Comment by IAM-1GRJK** [comment]
Thank you _jaxk25_.
This is hoped to be fixed in the future.
There will be a note added in the **README.md** and **how_to_link_to_style.css.txt**
Thank you,
_IAM-1GRJK_

**Comment by IAM-1GRJK** [comment]
If anyone knows how to fix this issue, then please get in touch by leaving a comment!

**Comment by jaxk25** [comment]
Thank you @IAM-1GRJK 
I hope that this gets fixed soon!
Thank you,
@jaxk25

**Comment by IAM-1GRJK** [comment]
Hello one again!
I can now tell you that the _green_on_black.css_ style is now working!
Thank you for your interest,
@IAM-1GRJK
