### ISSUE TITLE
Does not work on mobile.

### ISSUE THREAD

**Issue by jaxk25** [IAM-1GRJK/Example-Webpage#4]
On IOS, there is a free app called _sketch python_ although when I try to run it on there it will not work. Is this because it is not designed for mobile or do you think it is the app?
Thank you,
@jack25

**Comment by IAM-1GRJK** [comment]
Thank you for your concern @jaxk25. May I suggest checking that the app supports _flask_, _python3_, or even has _flask_ installed.
Thank you,
@IAM-1GRJK

**Comment by jaxk25** [comment]
Thanks @IAM-1GRJK!
Yes I can confirm that it runs _python3_ and it has _flask_ installed. Maybe it just doesn’t work on mobile? Thanks anyway!
Thank you, @jaxk25

**Comment by IAM-1GRJK** [comment]
Thank you once again @jack25.
I can now confirm that this does **not** work on mobile.
Thank you, 
@IAM-1GRJK
